server:
  port: 10001

spring:
  application:
    name: hikari-rpc-example-provider

# hikari-rpc config
hikari:
  rpc:
    register-address: 127.0.0.1:2181
    server-name: provider
    timeout: 2000
    host: 127.0.0.1
    port: ${server.port}
